import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/components/Header";
import { Footer } from "@/app/components/Footer";
import { ThemeProvider } from "@/components/ui/theme-provider"
import { FooterBar } from "./components/FooterBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <Header />
          {children}
          <Footer/>
          <div className="fixed bottom-6 left-0 w-full z-999 flex justify-center pointer-events-none">
              <div className="pointer-events-auto filter drop-shadow-[0_10px_30px_rgba(0,0,0,0.5)]">
                <FooterBar />
              </div>
           </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
